# TARGETS
#target: prerequisites
#	commands

#The commands are a series of steps typically to make the target,

#	need to start with a tab character, not space
# the prerequisites are file names, separated by spaces.
#	these files need to exist before the commands for the target are run

bulid:
	gcc -o ex_1_1 164975_Harshpatel_ex_1_1.c

execute:
	./ex_1_1
	
clean:
	rm -f *.o
	rm -f ex_1_1

